language: php
php:
  - 7.2
  - 7.3
  - 7.4
sudo: false
services:
  - mysql
  - postgresql
before_install:
  - phpenv config-add tests/config.ini
  - if [ $TRAVIS_PHP_VERSION == '7.2' ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
before_script:
  - mysql -e 'create database fusio;'
  - psql -c 'create database fusio;' -U postgres
script:
  - vendor/bin/psalm
  - vendor/bin/phpunit
env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql
