<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Token</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>

<div class="container mt-5" style="max-width:400px;">
  <h1>Token</h1>
  <p>You have successfully requested an Access-Token, please provide the Access-Token to your app, then you can close this window</p>
  <dl>
    <dt>Access-Token</dt>
    <dd><?php echo $access_token ?? ''; ?></dd>
    <dt>Expires-In</dt>
    <dd><?php echo $expires_in ?? ''; ?></dd>
    <dt>Refresh-Token</dt>
    <dd><?php echo $refresh_token ?? ''; ?></dd>
    <dt>Scope</dt>
    <dd><?php echo $scope ?? ''; ?></dd>
  </dl>
  <hr>
  <p class="text-muted text-end"><small>generated by <a href="https://www.fusio-project.org/">Fusio</a></small></p>
</div>

</body>
</html>
