name: TypeHub
on:
  push:
    branches:
      - master
jobs:
  typehub:
    name: TypeHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE fusio;" -uroot -proot
          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test1234';" -uroot -proot
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Setup Fusio
        env:
          APP_CONNECTION: 'pdo-mysql://root:test1234@localhost/fusio'
        run: |
          php bin/fusio migrate --no-interaction
          php bin/fusio api:push sdk --client_id="${{ secrets.TYPEHUB_CLIENT_ID }}" --client_secret="${{ secrets.TYPEHUB_CLIENT_SECRET }}" --filter=fusio --standalone
